### ISSUE TITLE
Need a _str_ method (different to show)

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#19]
[http://stackoverflow.com/questions/8144026/how-to-define-a-str-method-for-a-class](http://stackoverflow.com/questions/8144026/how-to-define-a-str-method-for-a-class)

**Comment by drvinceknight** [comment]
Worth checking if this is a 'done' thing though...

**Comment by theref** [comment]
Seems to be used when a module comes with presets built in, for example;
with normal form games, we might have a prebuilt Matching Pennies game that the user could load, then we would need a `__str__` method which would return "Matching Pennies"

**Comment by drvinceknight** [comment]
Not sure that's what I mean but we can chat about it tomorrow.

**Comment by drvinceknight** [comment]
This is a VERY minor point and should not stop us from pushing to trac for
review.

**Comment by theref** [comment]
agreed, if it's needed they'll tell us

**Comment by kcrisman** [comment]
Sometimes `_repr_` is what one uses, I believe.

**Comment by kcrisman** [comment]
Indeed, I'm not sure what purpose the `show` method serves, unless you were going to have a graphical representation of it via LaTeX or something.

As for str/repr, see [this SO question](http://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python).  Most Sage classes implement `_repr_` (try `sage: search_def('repr')`) rather than `__str__`.  Since you're inheriting directly from `SageObject`, you should see how this works [in the **repr** code](http://git.sagemath.org/sage.git/tree/src/sage/structure/sage_object.pyx#n112).

So my personal advice is to dump `show` and use `_repr_` (one underscore) as in most of the rest of the code, unless you have a compelling reason to have a separate (longer, presumably) `__str__` as well.

**Comment by drvinceknight** [comment]
On 5 Jun 2014 17:44, "kcrisman" notifications@github.com wrote:

> Indeed, I'm not sure what purpose the show method serves, unless you were
> going to have a graphical representation of it via LaTeX or something.
> 
> As for str/repr, see this SO question. Most Sage classes implement _repr_
> (try sage: search_def('repr')) rather than **str**. Since you're inheriting
> directly from SageObject, you should see how this works in the repr code.
> 
> So my personal advice is to dump show and use _repr_ (one underscore) as
> in most of the rest of the code, unless you have a compelling reason to
> have a separate (longer, presumably) **str** as well.

Dumping show and using _repr_ sounds good to me!

**Comment by drvinceknight** [comment]
Also, could be nice to include an option to get the the LateX code for rep
of a characteristic function game.

So LaTeX(g) would spit out the characteristic function in LaTeX form
(\begin{cases} etc...)? I'm guessing that's another inherited method on
Sage Object so worth seeing how that's done (for example when you type
latex(m) where m is a matrix you get the LaTeX code).  I don't think this
is a huge enhancement but could be nice...

**Comment by theref** [comment]
yes there is a `_latex_` method. For now I will rename `show` to `_repr_`, close this issue and create a new one.
The new issue will be for shortening `_repr_` (it's supposed to be quite concise) and creating a longer,  'prettier' `_latex_` method.
