### ISSUE TITLE
Possibly completely re-write the normal form game class...

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#48]
At present the `normal_form_game` class _inherits_ from the gambit game class through a process that uses `__new__`.

At present: this works.

**Another** approach would be to make `normal_form_game` inherit from SageObject and then when calling the Nash equilibrium solver if an algorithm corresponding to gambit is called **then** a gambit game object is created:

```
self.gambitgame = new_table(...)
```

and the equilibrium is obtained from that.

This would actually be in line with what is currently in development for the lrs algorithm implementation:

```
self.polytope = POLYTOPE REPRESENTATION
```

and the equilibrium is obtained from that...

**ONE HUGE ADVANTAGE OF THIS:** the normal form game class will exist whether or not gambit is installed. The various packages (lrs, gambit) will only be used when needed (for the solution).

At the same time, if gambit is installed one can still use the gambit api.

**Another advantage**: this is easier to implement.

A **DISADVANTAGE**: the game class that we'd end up with would often 'carry around' polytope and gambitgame attributes (is this a problem?)...

**Comment by meatballs** [comment]
You could create attributes on NormalFormGame which hold the various representations required by Gambit and LRS rather than the Gambit/LRS objects themselves. e.g.

```
self.polytope
self.gambit_table
```

The Gambit/LRS objects are then instantiated within NormalFormGame methods so that they are only created as and when required. Those methods can check the installation exists before attempting the instantiation.

You could also use a context manager (probably a 'with' statement) within the the NormalFormGame method to ensure that the Gambit/LRS object is destroyed just prior to returning your result.

**Comment by theref** [comment]
this is very similar to how we already call `self.matrix_to_game()` and `self.game_to_matrix()` in `__init__`, 
creating the equivalent for a polytope should be doable

**Comment by drvinceknight** [comment]
I think what Owen Campbell is suggesting is what I'm thinking as well.
Basically going to the gdot approach.

I'm slowly slowly thinking that that is in fact the best way. Once we've
closed a few more tickets using the current setup we'll branch and re-write
everything and have a real good think about the best way overall.

I was the main person saying that this approach wasn't the right way to go
but now I'm not sure...

**Comment by meatballs** [comment]
The disadvantage with this suggestion is that you create the Gambit/LRS object each time you want to use it and that could lead to performance issues if you're calling the methods many times.

If that's an issue, you could do both - create the possibility of self.gambit_game and use a persistence attribute to determine whether it's used or not.

**Comment by drvinceknight** [comment]
Yeah that's a good point. The big advantage I think is that we could
implement a very inefficient solver in pure sage so that even if no
optional packages were installed the class would still work. We'll work on
it once we've made some more progress (that's a very 'royal' 'we' :)).

**Comment by theref** [comment]
I'm going to post a link to this on trac, hopefully some of the sage dev guys will express an opinion too.

**Comment by drvinceknight** [comment]
Good idea.

**Comment by kcrisman** [comment]
I think that lightweight is good.  Especially since a lot of people will be using this (hopefully) for very simple 2x2 games in a pedagogical context, it would make the most sense to only instantiate what is necessary and inherit from something Sage-errific.  Like [this comment](https://github.com/theref/sage-game-theory/issues/48#issuecomment-46180685).  (You might also want to look at the graph theory code - I believe they have several different backends, including NetworkX and a C backend written just for Sage.)  Also, when it comes to the Gambit stuff, I don't know exactly how it will be used, but shouldn't there be some caching one could do?  I guess I don't know how it will interface with Sage.  You are right you definitely don't want to be creating a lot of those if you are doing millions of simulations using Gambit.  I don't know that you want to necessarily destroy the Gambit objects - would they typically be reused?  Though this is getting into waters I am not familiar with.

**Comment by theref** [comment]
Spent a while thinking about this today and came up with some thoughts:

**Mutability v's Speed**
If we construct NormalFormGame such that it allows the user to have edit access, we can't carry around `self.gambit_table` or `self.polytope` because there are big issues about them getting out of sync with each other. This will lead to performance issues with objects being repeatedly created every time they're needed.
If we construct it such that once completed (ie. all strategy profiles have an associated utility vector) it's immutable, we can then safely create `self.gambit_table` and `self.polytope` because we know they'll never change. This means that repeat calculations will be quicker, but if the user wants to edit the game, they have to start from scratch.

**Player Class**
This will not be accessible to the end user (there's no need). It allows us the have functions like `add_player` and `add_strategy` which makes the code far more flexible. Assuming the game is mutable (see above), an end user can add players and add strategies to those players as much as they want. This is not currently available in Gambit and I think is quite a nice addition.

**Comment by kcrisman** [comment]
I think this is okay (immutable games) because e.g. at least some vectors and matrices in Sage are immutable.  Just make sure to document this well and provide an easy-to-use `copy` method - and you may need to take deep copy considerations into account as well, I don't know.

Especially if some of the stuff can be copied with the copy (e.g. the gambit stuff) once created, this would seem the way to go for me.

Player class: you may want to look at this as analogous to some of the matrix methods which do stuff like this (add rows or whatnot) but return a new matrix.

PS I just talked to some people who are familiar with Gambit at a conference, that was encouraging!

**Comment by theref** [comment]
Personally I'm not sure that performance issues are really a problem. Once the Nash equilibria have been found why would the process be repeated? Someone may want to compare 2 algorithms, but a polytope would still have to be created for LRS for example. I think the ability to change a game quickly and easily would be far more useful for the end user.

Another thought, we could have 2 classes. An immutable class that inherits from the mutable one specifically for when people want to repeat things?

**Comment by drvinceknight** [comment]
> Personally I'm not sure that performance issues are really a problem. Once the Nash equilibria have been found why would the process be repeated? Someone may want to compare 2 algorithms, but a polytope would still have to be created for LRS for example. I think the ability to change a game quickly and easily would be far more useful for the end user.

I think I agree with James. I don't think there is much advantage to be gained for the rare occasions where this would happen... 

> Another thought, we could have 2 classes. An immutable class that inherits from the mutable one specifically for when people want to repeat things

Unless worrying about speeding up repetition is indeed the right way to go I don't think this is worth doing...

**Comment by theref** [comment]
I think this has been covered now, there are a couple of small issues we need to fix and they have their own tickets now.
